// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class Character
    {
        public Character()
        {
            PokemonOwneds = new HashSet<PokemonOwned>();
        }

        public int CharacterId { get; set; }
        public int PlayerId { get; set; }
        public string Link { get; set; }
        public string CharacterName { get; set; }
        public string GameMode { get; set; }

        public virtual Player Player { get; set; }
        public virtual ICollection<PokemonOwned> PokemonOwneds { get; set; }
    }
}