// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class Player
    {
        public Player()
        {
            Characters = new HashSet<Character>();
        }

        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
        public string DiscordId { get; set; }

        public virtual ICollection<Character> Characters { get; set; }
    }
}