// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class PokemonStat
    {
        public int PokemonId { get; set; }
        public bool DualType { get; set; }
        public string TypeOne { get; set; }
        public string TypeTwo { get; set; }
        public int HitPoints { get; set; }
        public int Attack { get; set; }
        public int Defense { get; set; }
        public int SpecialAttack { get; set; }
        public int SpecialDefense { get; set; }
        public int Speed { get; set; }
        public int EvAtk { get; set; }
        public int EvSatk { get; set; }
        public int EvAny { get; set; }

        public virtual PokemonOwned Pokemon { get; set; }
    }
}