// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class Pokedex
    {
        public string PokemonName { get; set; }
        public bool DualType { get; set; }
        public string TypeOne { get; set; }
        public string TypeTwo { get; set; }
    }
}