// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class PokemonOwned
    {
        public int CharacterId { get; set; }
        public int PokemonId { get; set; }
        public string PokemonName { get; set; }

        public virtual Character Character { get; set; }
    }
}