// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class Skill
    {
        public int CharacterId { get; set; }
        public int Acrobatics { get; set; }
        public int Athletics { get; set; }
        public int Charm { get; set; }
        public int Combat { get; set; }
        public int Command { get; set; }
        public int GeneralEd { get; set; }
        public int MedicineEd { get; set; }
        public int OccultEd { get; set; }
        public int PokemonEd { get; set; }
        public int TechnologyEd { get; set; }
        public int Focus { get; set; }
        public int Guile { get; set; }
        public int Intimidate { get; set; }
        public int Intuition { get; set; }
        public int Perception { get; set; }
        public int Stealth { get; set; }
        public int Survival { get; set; }

        public virtual Character Character { get; set; }
    }
}