// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace The_Prodigal_Son.Models
{
    public partial class TypeEffect
    {
        public string TypeName { get; set; }
        public int VsNormal { get; set; }
        public int VsFire { get; set; }
        public int VsWater { get; set; }
        public int VsGrass { get; set; }
        public int VsElectric { get; set; }
        public int VsIce { get; set; }
        public int VsFighting { get; set; }
        public int VsPoison { get; set; }
        public int VsGround { get; set; }
        public int VsFlying { get; set; }
        public int VsPsychic { get; set; }
        public int VsBug { get; set; }
        public int VsRock { get; set; }
        public int VsGhost { get; set; }
        public int VsDragon { get; set; }
        public int VsDark { get; set; }
        public int VsSteel { get; set; }
        public int VsFairy { get; set; }
    }
}